const fs = require("fs");
const path = require("path");

const commandsDir = path.resolve(__dirname, "../src/data/gitCommands");
const indexFile = path.join(commandsDir, "index.js");

const jsonFiles = fs
  .readdirSync(commandsDir)
  .filter(file => file.endsWith(".json") && file !== "index.js");

const validJsonFiles = [];

for (const file of jsonFiles) {
  const filePath = path.join(commandsDir, file);
  try {
    const content = fs.readFileSync(filePath, "utf-8").trim();
    if (!content) {
      console.warn(`⚠️ Skipping empty file: ${file}`);
      continue;
    }
    const parsed = JSON.parse(content);
    if (!Array.isArray(parsed) || parsed.length === 0) {
      console.warn(`⚠️ Skipping empty or invalid array file: ${file}`);
      continue;
    }
    validJsonFiles.push(file);
  } catch (e) {
    console.warn(`⚠️ Skipping invalid JSON file: ${file} (${e.message})`);
  }
}

if (validJsonFiles.length === 0) {
  console.error("❌ No valid JSON files found to include in index.js");
  process.exit(1);
}

const imports = validJsonFiles
  .map((file, i) => `import data${i} from "./${file}";`)
  .join("\n");

const exportsArray = validJsonFiles
  .map((_, i) => `...data${i}`)
  .join(",\n  ");

const indexContent = `// Auto-generated by scripts/generateIndex.js
${imports}

const gitCommands = [
  ${exportsArray}
];

export default gitCommands;
`;

fs.writeFileSync(indexFile, indexContent);

console.log(`✅ index.js updated with ${validJsonFiles.length} JSON files.`);
